phoenix.lo: /home/chenke/cwork/phoenix/phoenix.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/chenke/cwork/phoenix $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/chenke/cwork/phoenix/phoenix.c -o phoenix.lo 
$(phplibdir)/phoenix.la: ./phoenix.la
	$(LIBTOOL) --mode=install cp ./phoenix.la $(phplibdir)

./phoenix.la: $(shared_objects_phoenix) $(PHOENIX_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_phoenix) $(PHOENIX_SHARED_LIBADD)

